version: "3"

services:
  webhook:
    restart: unless-stopped
    image: almir/webhook
    container_name: webhook
    command:
      - "-verbose"
      - "-port=${TRAEFIK_OPS_PORT-9000}"
      - "-hooks=/app/.webhook/hooks.json"
      - "-urlprefix=${WEBHOOK_URL_PREFIX:-hooks}"
      - "-http-methods=${WEBHOOK_HTTP_METHOD:-PATCH}"
      - "-hotreload"
    volumes:
      - "./:/app"
    ports:
      - "${TRAEFIK_OPS_PORT-9000}"
    labels:
      - "traefik.http.routers.webhook.rule=Host(`${DOMAIN}`) && PathPrefix(`/${WEBHOOK_URL_PREFIX:-hooks}`)"
      - "traefik.http.routers.webhook.entrypoints=ops"
      - "traefik.http.routers.webhook.middlewares=admin"
      - "traefik.http.routers.webhook.tls.certresolver=letsencrypt"
networks:
  default:
    external:
      name: web
