version: "3.3"

services:
  traefik:
    restart: unless-stopped
    image: "traefik:${TRAEFIK_IMAGE_TAG:-v2.2}"
    container_name: "traefik"
    command:
      - "--log.level=${TRAEFIK_LOG_LEVEL:-info}"
      - "--api.dashboard=${TRAEFIK_API_DASHBOARD:-false}"
      - "--accesslog.filters.statuscodes=400-599"
      - "--accesslog.filters.retryattempts=true"
      - "--accesslog.filters.minduration=100ms"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=${TRAEFIK_EXPOSED_BY_DEFAULT:-true}"
      - "--providers.docker.network=${DOCKER_NETWORK:-web}"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.ops.address=:${TRAEFIK_OPS_PORT:-9000}"
      - "--entrypoints.ops.http.tls=letsencrypt"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=letsencrypt"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.caserver=${LETSENCRYPT_SERVER:-https://acme-v02.api.letsencrypt.org/directory}"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "${TRAEFIK_OPS_PORT-9000}:${TRAEFIK_OPS_PORT-9000}"
    volumes:
      - "./.traefik:/traefik"
      - "./:/app"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.http.middlewares.admin.basicauth.usersfile=/app/${TRAEFIK_PASSWD_FILE:-users}"
      - "traefik.http.routers.traefik-api.middlewares=admin"
      - "traefik.http.routers.traefik-api.service=api@internal"
      - "traefik.http.routers.traefik-api.rule=Host(`${DOMAIN}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      - "traefik.http.routers.traefik-api.entrypoints=ops"
      - "traefik.http.routers.traefik-api.tls.certresolver=letsencrypt"
    logging:
      driver: ${DOCKER_LOG_DRIVER:-journald}
networks:
  default:
    external:
      name: "${DOCKER_NETWORK:-web}"
